name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install root dependencies
      run: npm install
    - name: Install React app dependencies
      run: |
        cd playwright-react-app
        npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start React app
      run: |
        cd playwright-react-app
        npm run dev &
    - name: Run Playwright tests
      run: npx playwright test tests/login.spec.ts
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
